### ISSUE TITLE
https://burnermap.com/json?camps=1 not returning BMOrg API ID for camps

### ISSUE THREAD

**Issue by cdcilley** [wikiworldorder/burnermap#12]
The JSON export link is using numerical values for the BMOrg apiID instead of the string values that have been used since last year.  As I remember, this worked last year...

I've highlighted in **bold** the disparate values.

BurnerMaps JSON for !Zoom! reads:
{
"name":"!Zoom!",
"adClock":"6:30",
"adRing":"Esplanade",
"adSide":"",
"x":315,
"y":338,
"size":7,
"id":280,
**"apiID":"91"**
}

BMOrg API JSON for !Zoom! reads:
{
        **"uid": "a1X0V000003WsFeUAK"**,
        "year": 2018,
        "name": "!Zoom!",
        "url": "http://campzoom.org",
        "contact_email": "zoomy@campzoom.org",
        "hometown": "Oakland",
        "description": "Undersea Oasis of fire!  Join us for our daily fire spinning lessons and our nights of fire!  Firebase ball tuesday after dark and late wednesday for fire dodgeball.  Our playground equipment is open 24/7 but one new piece will be operated by zoomer direction only.  Of just chill in our bubble lounge or black light snail dome.",
        "location": {
            "string": "Esplanade & 6:30",
            "frontage": "Esplanade",
            "intersection": "6:30",
            "intersection_type": "&",
            "dimensions": null
        },
        "location_string": "Esplanade & 6:30"
    }

**Comment by wikiworldorder** [comment]
Hi cdcilley, Thanks for catching this! I have just fixed this so it that JSON should once again provide the string BMOrg apiID. Linking the apiID is currently only support for the current year's camps, but I think we should be good on this front for now.
