### ISSUE TITLE
Villages are not complete

### ISSUE THREAD

**Issue by TomHAnderson** [wikiworldorder/burnermap#14]
I've perused the code and cannot find a Village maintainer section.  I'm not proposing that be added but I need you to move "Cosmiquarium Village" from a camp to a village.

**Comment by wikiworldorder** [comment]
Thanks Tom! I've added you village to the list.

In past years, I've maintained that list personally to avoid it being too crowd-sourced. I would love to find an annual list of 'official' villages which include multiple camps. But I am also open to opening up that list to include non-officially-placed villages, like the camps. ;) <3

**Comment by TomHAnderson** [comment]
2. Cosmiquarium Village2:15 & Esplanade in 404: Village Not Found
 
Now my friends camping with me are still in a camp named Cosmiquarium Village but not in a village.  Can you move them to the village?

**Comment by TomHAnderson** [comment]
So I have a couple ideas for the data:

1. If it's a list you're maintaining put it in a fixture (seed).
2. Allow users to create villages and have a method to peer (or you) review them.

**Comment by TomHAnderson** [comment]
a 404 on a map is odd.  and "Village Not Found" is not greped in the code.  Where is this error coming from?

**Comment by TomHAnderson** [comment]
A note on fixtures:  When I create fixtures they are repeatable so you can run the fixtures at any time.  e.g. https://github.com/API-Skeletons/zf-doctrine-audit/blob/master/src/Fixture/RevisionTypeFixture.php  This is just a suggestion as I don't grok Laraval.

**Comment by wikiworldorder** [comment]
Alrighty Tom, I think I've fixed the village association for your friends into the village. It also seems I need to double-check that campers are correctly associated with their village. And thank you very much for all this advice on how to handle this! <3
