### ISSUE TITLE
Inconsistent License

### ISSUE THREAD

**Issue by justinormont** [wikiworldorder/burnermap#2]
The license is listed as both GPL and MIT.

/LICENSE file says GPL:
https://github.com/wikiworldorder/burnermap/blob/d07d5e5427b677fef0b299e3eec329c49763064f/LICENSE#L1

/README.md says MIT:
https://github.com/wikiworldorder/burnermap/blob/d07d5e5427b677fef0b299e3eec329c49763064f/README.md#L5

**Comment by wikiworldorder** [comment]
Thanks! I think I've taken care of this oversight in a fresh commit.
