### ISSUE TITLE
Incorrect labels for dates

### ISSUE THREAD

**Issue by muloka** [wikiworldorder/burnermap#20]
The corresponding dates have:

* incorrect days of the week labels (i.e. 8/31 should be a Saturday)
* incorrect day of the man burn and temple burn (i.e. 8/31 should the man burn, and 9/1 should be the temple burn)

![dates](https://i.imgur.com/6ECEnQC.png)

**Comment by muloka** [comment]
Would pull request #18 solve this issue?

**Comment by wikiworldorder** [comment]
Sorry for my delays on this! I've correct my own admin user error, initially plugging this year's date range settings as 2018 instead of 2019. This threw off the Saturday-detection logic. Thanks so much!
